import 'package:drift/drift.dart' as i0;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
i0.OnUpgrade stepByStep({MigrationStrategy, required Future<Null> Function(dynamic m, dynamic schema) from1To2, required Future<Null> Function(dynamic m, dynamic schema) from2To3}) {
  return i0.Migrator.stepByStepHelper(step: (currentVersion, database) async {
    switch (currentVersion) {
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  });
}
